import http.client

url = '127.0.0.1:8000'
connection = http.client.HTTPConnection(url)
#good input
connection.request('POST', '/animals', body='{"Cat":10,"Dog":5}')
response = connection.getresponse()
print(response.read())
connection.request('POST', '/animals', body='{"Bat":12}')
response = connection.getresponse()
print(response.read())
connection.request('POST', '/animals', body='{"Bat":12}')
response = connection.getresponse()
print(response.read())
connection.request('DELETE', '/animals/bat')
response = connection.getresponse()
print(response.read())
connection.request('POST', '/animals/bat?quant=2')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals/bat?option=increment&quant=6')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals/bat?option=decrement&quant=2')
response = connection.getresponse()
print(response.read())
connection.request('GET', '')
response = connection.getresponse()
print(response.read())
connection.request('GET', '/animals')
response = connection.getresponse()
print(response.read())


#Now for the bad inPOST
connection.request('POST', '/animals/bat?quant=-12')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals/bat?option=increment&madness=6')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals/bat?option=nothing&madness=6')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals?option=decrement&quant=2')
response = connection.getresponse()
print(response.read())
connection.request('POST', '/animals/bat')
response = connection.getresponse()
print(response.read())
connection.request('PUT', '/animals/bat?option=decrement&quant=2000')
response = connection.getresponse()
print(response.read())
connection.request('FLY', '/animals/bat?option=decrement&quant=2000')
response = connection.getresponse()
print(response.read())
connection.request('FADS', 'gawcvsawr')
response = connection.getresponse()
print(response.read())
connection.request('POST', '/a//t?option=de/crement&quant=20asdg00')
response = connection.getresponse()
print(response.read())
